packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.14.0

  "@trpc/client": ^11.0.4
  "@trpc/server": ^11.0.4
  "@trpc/react-query": ^11.0.4

  "@tanstack/react-query": ^5.72.2

  "@arcjet/next": ^1.0.0-beta.5
  "@arcjet/decorate": ^1.0.0-beta.5

  tailwindcss: ^4.1.3
  "@tailwindcss/postcss": ^4.1.3

  eslint: ^9.24.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  zod: ^3.24.2

catalogs:
  next:
    next: ^15.3.0
    "@next/eslint-plugin-next": ^15.3.0
    "@next/bundle-analyzer": ^15.3.0

  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.2

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@vercel/speed-insights"
  - core-js
  - core-js-pure
  - esbuild
  - sharp
