packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.13.4
  "@types/node": ^22.15.17

  "@trpc/client": ^11.1.2
  "@trpc/server": ^11.1.2
  "@trpc/react-query": ^11.1.2

  "@tanstack/react-query": ^5.75.7

  "@arcjet/next": ^1.0.0-beta.7
  "@arcjet/decorate": ^1.0.0-beta.7

  tailwindcss: ^4.1.5
  "@tailwindcss/postcss": ^4.1.5

  eslint: ^9.26.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  zod: ^3.24.4

catalogs:
  next:
    next: ^15.3.2
    "@next/eslint-plugin-next": ^15.3.2
    "@next/bundle-analyzer": ^15.3.2

  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@vercel/speed-insights"
  - core-js
  - core-js-pure
  - esbuild
  - sharp
