packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.14.1

  "@trpc/client": ^11.1.0
  "@trpc/server": ^11.1.0
  "@trpc/react-query": ^11.1.0

  "@tanstack/react-query": ^5.74.4

  "@arcjet/next": ^1.0.0-beta.6
  "@arcjet/decorate": ^1.0.0-beta.6

  tailwindcss: ^4.1.4
  "@tailwindcss/postcss": ^4.1.4

  eslint: ^9.24.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  zod: ^3.24.3

catalogs:
  next:
    next: ^15.3.1
    "@next/eslint-plugin-next": ^15.3.1
    "@next/bundle-analyzer": ^15.3.1

  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@vercel/speed-insights"
  - core-js
  - core-js-pure
  - esbuild
  - sharp
