packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.13.14

  "@trpc/client": ^11.0.0
  "@trpc/server": ^11.0.0
  "@trpc/react-query": ^11.0.0

  "@tanstack/react-query": ^5.69.0

  "@arcjet/next": ^1.0.0-beta.5
  "@arcjet/decorate": ^1.0.0-beta.4

  tailwindcss: ^4.0.17
  "@tailwindcss/postcss": ^4.0.17

  eslint: ^9.23.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  zod: ^3.24.2

catalogs:
  next:
    next: ^15.2.4
    "@next/eslint-plugin-next": ^15.2.4
    "@next/bundle-analyzer": ^15.2.4

  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@vercel/speed-insights"
  - core-js
  - core-js-pure
  - esbuild
  - sharp
